[package]
name = "builder-rust"
description = "A builder tool to generate template colorschemes"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Jamy Golden <code@jamygolden.com>"]
homepage = "https://github.com/tinted-theming/builder-rust"
repository = "https://github.com/tinted-theming/builder-rust"
keywords = ["cli", "base16", "shell"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.75"
base16_color_scheme = "0.3.1"
clap = "4.4.10"
dirs = "5.0.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"
